### ISSUE TITLE
Document is undefined

### ISSUE THREAD

**Issue by ducyb782001** [markjaniczak/use-scan-detection#14]
I cannot use this library, anyone can help me with this please

**Comment by markjaniczak** [comment]
I'm assuming you're rendering react in a non-browser environment, like on Next.js?

If that's the case you'll need to conditionally render the component that uses this hook as that was not a consideration when writing the library.

**Comment by ducyb782001** [comment]
Yes i'm using next.js i use your code and make some change in container:document and it works
