### ISSUE TITLE
Suppress special characters

### ISSUE THREAD

**Issue by logan2d** [markjaniczak/use-scan-detection#15]
If I focus in a text field, and use my scan gun without the library, there are no special characters.  If I go through your library to populate the text field, I am getting special characters in the code/value.  See below where I had to remove a 'Shift' that was populating.  I'm now also seeing an F8 in the code.  I don't want to have to replace every character. Is there a way to suppress them?

    useScanDetection({
        onComplete: (code) => { handleScan(code) },
        minLength: 13 // EAN13  
    });

    const handleScan = (code) => {
        code = code.replace(/Shift/g, "");
        props.setValue(code);   
      }

**Comment by Minh8181-blz** [comment]
I encounter the same issue. My barcode starts with P and the scan output is ShiftP...

**Comment by mssadewa** [comment]
I've the same issue.
When I scan barcode with value **ABC1234** useScanDetection return **ShiftAShiftBShiftC1234**.

**Comment by btxTruong** [comment]
I think the `keydown` event includes the modifier key (CTRL, SHIFT, META, ALT) so that's the reason the output includes **Shift...**

**Comment by markjaniczak** [comment]
Hey all, I've released [`symbology-scanner`](https://github.com/markjaniczak/symbology-scanner) which provides the same functionality as `use-scan-detection` but is better tested and includes additional features such as:
- Both a react and vanilla JS package
- Ability to match against multiple specific Symbologies (e.g. EAN-13, QR, Codabar)

Moreover, it solves this specific issue by escaping modifier keys (Shift, Control, Meta and Alt).
